name: edzesnaplo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # További csomagok
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.1
  cloud_firestore: ^5.6.10
  firebase_messaging: ^15.2.8
  google_fonts: ^6.2.1
  fl_chart: ^0.63.0
  percent_indicator: ^4.2.2


  # Többnyelvűség támogatás
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true   # <-- Ez kell, hogy automatikusan generálja az lokalizációs fájlokat
